name: Publish

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  continuous-integration:
    uses: ./.github/workflows/continuous-integration.yml
    secrets: inherit

  publish:
    runs-on: ubuntu-latest
    needs: continuous-integration

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js (NPM)
        run: echo "Setting up Node 18.x pointed to NPM..."

      - name: Install Dependencies
        run: echo "Installing dependencies..."

      - name: Publish to NPM
        # run: yarn publish --new-version 2.2.0 --access public
        run: echo "Publishing to NPM"

      - name: Setup Node.js (GPR)
        run: echo "Setting up Node 18.x pointed to GPR..."

      - name: Publish to GPR
        # run: yarn publish --new-version 2.2.0 --access public
        run: echo "Publishing to GitHub"
